---
ci:
  autoupdate_schedule: monthly
  autofix_commit_msg: |
    [pre-commit.ci] Apply automatic pre-commit fixes
  skip: []

repos:
#  - repo: local
#    hooks:
#      - id: custom-build
#        name: custom-build
#        entry: bash -c 'source build.sh'
#        language: system
#        # types: [ python ]
#        pass_filenames: false
#        verbose: true
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      # -   id: end-of-file-fixer
      - id: check-yaml
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files

#  - repo: https://github.com/igorshubovych/markdownlint-cli
#    rev: v0.46.0
#    hooks:
#      - id: markdownlint
#        # '--fix'
#        args: [ 'content/**/*.md', '--config', '.markdownlintrc']
  - repo: https://github.com/executablebooks/mdformat
    rev: 1.0.0  # Use the ref you want to point at
    hooks:
      - id: mdformat
        # Optionally add plugins
        additional_dependencies:
          - mdformat-gfm
          - mdformat-black
#- repo: https://github.com/jackdewinter/pymarkdown
#  rev: v0.9.8
#  hooks:
#    - id: pymarkdown
#      pass_filenames: false
#      args:
#        - --config
#        - pymarkdown_config.json
#        - scan
#        - .
#        - ./docs
