[[projects]]
slug = "Hicmah"
name = "Hicmah"
description = "Hicmah - Hit Counter Module and Handler"
url = "https://github.com/matthewdeanmartin/Hicmah"
repository_url = "https://github.com/matthewdeanmartin/Hicmah"
tags = [
    "analytics",
    "handler",
    "hit-counter",
    "javascript",
    "module",
    "web-development",
]
status = "active"
primary_language = "N/A"

[projects.cms]
suppress = false
package_links = []

[[projects]]
slug = "ai_fish_tank"
name = "ai_fish_tank"
description = "Fish tank that has a story going on"
url = "https://github.com/matthewdeanmartin/ai_fish_tank"
tags = [
    "aquarium",
    "artificial-intelligence",
    "game",
    "interactive-fiction",
    "python",
    "simulation",
    "storytelling",
]
status = "active"
repository_url = "https://github.com/matthewdeanmartin/ai_fish_tank"
primary_language = "Python"
