[[packages]]
package_name = "ai-shell"
downloads_monthly = 0
version = "1.0.4"
summary = "Filesystem Shell interface that an OpenAI Assitant can use as a tool."
docs_url = "https://github.com/matthewdeanmartin/ai_shell"
last_updated = "2025-12-20"
github_repo = "matthewdeanmartin/ai_shell"
tags = [
    "openai",
    "chatgpt",
]

[[packages]]
package_name = "bash2gitlab"
downloads_monthly = 0
version = "0.9.9"
summary = "Compile bash to gitlab pipeline yaml"
docs_url = "https://pypi.org/project/bash2gitlab/"
last_updated = "2025-12-20"
github_repo = "matthewdeanmartin/bash2gitlab"
tags = [
    "bash",
    "gitlab",
]

[[packages]]
package_name = "bitrab"
downloads_monthly = 0
version = "0.1.0"
summary = "Compile bash to gitlab pipeline yaml"
docs_url = "https://pypi.org/project/bitrab/"
last_updated = "2025-12-20"
github_repo = "matthewdeanmartin/bitrab"
tags = [
    "bash",
    "gitlab",
]
